# -*- coding: utf-8 -*-
"""Introduction to Power  BI, Charts, DAX &  Creating Reports

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjiAAuQ9YbQy-LhhcI7Qg4kp72eGxcJK

Assignment: Introduction to Power BI, Charts, DAX & Reports
Question 1: Define Power BI and its Components
Answer:

Power BI is a business analytics tool by Microsoft used to visualize data, create reports, and share insights.

Key Components:
1. Power BI Desktop
Main development tool
Used to create reports, data models, and visuals
2. Power BI Service
Cloud-based platform
Used to publish and share dashboards
3. Power BI Mobile
Mobile app
Access reports on phone/tablet
4. Power BI Gateway
Connects on-premise data to cloud
Enables real-time data refresh
Question 2: Pie vs Donut & Bar vs Column
Answer:
Pie Chart vs Donut Chart
Pie Chart	Donut Chart
Full circle	Hollow center
Simple comparison	Shows additional info in center

Use Case:

Pie → Market share
Donut → Sales % with total in center
Bar Chart vs Column Chart
Bar Chart	Column Chart
Horizontal	Vertical
Long labels	Time-based data

Use Case:

Bar → Sales by category
Column → Monthly trends
Question 3: Data Modeling Concepts
Answer:
Star Schema vs Snowflake Schema
Star Schema	Snowflake Schema
Simple	Complex
Fast queries	Normalized tables
Primary Key vs Foreign Key
Primary Key: Unique identifier
Foreign Key: Links tables
Cardinality Importance
Defines relationship type (1:1, 1:M)
Affects performance and accuracy
Question 4: Calculated Column vs Measure
Answer:
Calculated Column	Measure
Row-level	Aggregate-level
Stored in table	Calculated dynamically
Row Context
Calculation for each row
Example: Profit = Sales - Cost
Filter Context
Applies filters to calculations
Example: Total Sales for Region = West
Question 5: Report vs Dashboard
Answer:
Report	Dashboard
Multiple pages	Single page
Detailed	Summary
Interactive	Less interactive
Question 6: Visuals Creation (Superstore Dataset)
Answer:
Steps:
1. Clustered Bar Chart
Axis → Sub-Category
Values → Sales
2. Donut Chart
Legend → Region
Values → Sales
Note:



Question 7: DAX Measures & Visuals
Answer:
DAX Measures:
Total Profit = SUM([Profit])

Average Discount = AVERAGE([Discount])
Visuals:
KPI Card → Total Profit & Avg Discount
Line Chart → Profit vs Month
Steps:
Create measures
Add KPI visual
Add Line chart
Drag Order Date (Month)
Question 8: Percentage of Total Sales (DAX)
Answer:
Sales % =
DIVIDE(
    SUM([Sales]),
    CALCULATE(SUM([Sales]), ALL(Product_category))
)
Explanation:
Calculates contribution of each category
Used in Pie/Donut chart
Question 9: Waterfall Chart Analysis
Answer:
DAX Measure:
Total Profit = SUM([Profit])
Steps:
Insert Waterfall chart
Category → Sub-Category
Values → Total Profit
Add Slicer → Region
Business Insights:
Some sub-categories generate high profit
Some cause losses
Profit varies by region
Recommendations:
Focus on high-profit categories
Reduce discounts in loss areas
Optimize logistics cost
Note:



Question 10: Health Dashboard (VitaTrack)
Answer:
Dashboard Design:
1. Balanced Lifestyle
KPI → Avg Steps, Sleep, Calories
Bar/Line chart
2. Heart Risk Factors
Scatter plot → BMI vs Heart Rate
Filter → Heart Disease
3. Sleep vs Activity
Scatter plot → Sleep vs Steps
4. BMI Analysis
Column chart → BMI by Age & Gender
5. Smoking & Alcohol Impact
Bar chart → Heart Rate vs Smoking
Bar chart → BP vs Alcohol
6. Segmentation
Use clustering (or groups):
Active
Moderate
Risk
Business Insights:
Low sleep + high BMI → higher risk
Smokers → higher heart rate
Exercise reduces BP
Recommendations:
Promote fitness programs
Personalized health alerts
Target high-risk users
"""

from IPython.display import Image
Image('/content/54042d87-c2c9-4185-b37b-18fb3db406bd.jpg')

